### Title: <span style='color:red;'>US_GUN_VIOLENCE</span>

### Introduction:
##### Project Description
Human societies are plagued with several social issues that can be life-threatening at times. A notable case is the issue of gun violence in the United States which results in tens of thousands of deaths and injuries annually. In this project we perform a deep exploration of gun violence incidents reported in the US.

##### Dataset Description:
The dataset used in this project was obtained from [source](https://www.kaggle.com/jameslko/gun-violence-data)
##### Overall Goal:
<span style='color:red;'>My goal is to explore this data to draw useful insights from data about the gun violence in the US.</span>

##### Specific goals
At the end of this exploratory analysis, I hope to answer the following questions:
1. how much has has gun violence increased over the years?
2. how much has deaths per year due to gun violence changed over the years?
3. where in the US is gun violence most prevalent

### Load Modules and Data

For the purpose of analysis, I would be making use of the following modules. Next, I would load in my data.

In [1]:
#imports
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [37]:
import os
os.chdir("F:/micro masters/PYTHON/US Gun Violence")

In [38]:
# load data
guns = pd.read_csv("guns.csv")


### Preview of Data

In [12]:
guns.head(5)

,incident_id,date,state,city_or_county,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,congressional_district,...,longitude,n_guns_involved,notes,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,sources
0,461105,1/1/2013,Pennsylvania,Mckeesport,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,14.0,...,-79.8559,NaN,Julian Sims under investigation: Four Shot and...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...
1,460726,1/1/2013,California,Hawthorne,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,43.0,...,-118.3330,NaN,Four Shot; One Killed; Unidentified shooter in...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...
2,478855,1/1/2013,Ohio,Lorain,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,9.0,...,-82.1377,2.0,NaN,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...
3,478925,1/5/2013,Colorado,Aurora,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,6.0,...,-104.8020,NaN,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...
4,478959,1/7/2013,North Carolina,Greensboro,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,6.0,...,-79.9569,2.0,Two firearms recovered. (Attempted) murder sui...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...

In [5]:
guns.shape

(239677, 24)

### 1. Data quality Assessment
**Goal**:
To perform an initial assessment of the data quality that would allow me to go to the next steps of my analysis.

First, I will take out of the initial data, the relevant subset that interests my exploration of the data.

Secondly, to complete this step, I would be examining the dataset for the following data quality issues:
- Accuracy of field values
- Missing values
- Duplicate entries

#### IDENTIFYING RELEVANT COLUMNS

To simplify the data, the first thing I want to do is to have a look at the variable names to see which ones contain the data needed for any kind of intuitive analysis that I am interested in.

In [13]:
guns.columns

Index(['incident_id', 'date', 'state', 'city_or_county', 'n_killed',
       'n_injured', 'incident_url', 'source_url',
       'incident_url_fields_missing', 'congressional_district', 'gun_stolen',
       'gun_type', 'latitude', 'location_description', 'longitude',
       'n_guns_involved', 'notes', 'participant_age', 'participant_age_group',
       'participant_gender', 'participant_relationship', 'participant_status',
       'participant_type', 'sources'],
      dtype='object')

**comment:** Looking at the variable names, I will be removing the following columns: ('incident_id', 'incident_url', 'source_url',  'incident_url_fields_missing', 'congressional_district', 'gun_stolen','gun_type','n_guns_involved', 'notes', 'sources', 'location_description', 'participant_status', 'participant_type','participant_gender', 'participant_relationship',)

In [39]:
new_guns=guns[['date', 'state', 'city_or_county', 'n_killed','n_injured', 'latitude', 'longitude', 'participant_age', 'participant_age_group']]
new_guns.shape

(239677, 9)

#### PROFILING THE DATA

From above, I have 9 variables and 239677 observations from the dataset that are of interest to me.

The first step towards any data analysis is to have an overview of the data. To help me achieve this goal, I would be using the pandas profiling method.

In [7]:
import pandas_profiling as pp

In [8]:
profile=pp.ProfileReport(new_guns)
profile

In [9]:
new_guns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 9 columns):
date                     239677 non-null object
state                    239677 non-null object
city_or_county           239677 non-null object
n_killed                 239677 non-null int64
n_injured                239677 non-null int64
latitude                 231754 non-null float64
longitude                231754 non-null float64
participant_age          147379 non-null object
participant_age_group    197558 non-null object
dtypes: float64(2), int64(2), object(5)
memory usage: 16.5+ MB

**ASSESSMENT OF FEILD VALUES**

In [10]:
import numpy as np
new_guns.describe(include=np.float64)

            latitude      longitude
count  231754.000000  231754.000000
mean       37.546598     -89.338348
std         5.130763      14.359546
min        19.111400    -171.429000
25%        33.903400     -94.158725
50%        38.570600     -86.249600
75%        41.437375     -80.048625
max        71.336800      97.433100

In [40]:
new_guns['date']=pd.to_datetime(new_guns['date'])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:

for column in new_guns:
    Categories=[]
    new_guns[column]=pd.Categorical(new_guns[column])
    Categories.append([column, new_guns[column].cat.categories])
    
    print('\n')
    print(Categories)
    print(' ')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

[['date', DatetimeIndex(['2013-01-01', '2013-01-05', '2013-01-07', '2013-01-19',
               '2013-01-21', '2013-01-23', '2013-01-25', '2013-01-26',
               '2013-02-02', '2013-02-03',
               ...
               '2018-03-22', '2018-03-23', '2018-03-24', '2018-03-25',
               '2018-03-26', '2018-03-27', '2018-03-28', '2018-03-29',
               '2018-03-30', '2018-03-31'],
              dtype='datetime64[ns]', length=1725, freq=None)]]



[['state', Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object')]]



[['city_or_county', Index(['Abbeville', 'Abbotsford', 'Abbott', 'Abbott Township', 'Abbottstown',
       'Abercrombie', 'Aberdeen', 'Abilene', 'Abingdon', 'Abington',
       ...
       'Zion', 'Zion (Beach Park)', 'Zion Grove', 'Zionsville', 'Zionville',
       'Zumbro Falls', 'Zumbrota', 'Zuni (Zuni Pueblo)', 'Zwolle',
       'jefferson parish (county)'],
      dtype='object', length=12898)]]



[['n_killed', Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16, 17, 27, 50], dtype='int64')]]



[['n_injured', Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 25, 53],
           dtype='int64')]]



[['latitude', Float64Index([19.1114, 19.1127,    19.2, 19.2017, 19.4243, 19.4331, 19.4475,
              19.4554, 19.4578, 19.4581,
              ...
              67.5533, 70.1981, 70.6698, 71.2906, 71.2921, 71.2997,    71.3,
              71.3001, 71.3005, 71.3368],
             dtype='float64', length=101240)]]



[['longitude', Float64Index([           -171.429,            -166.541,            -166.097,
              -165.71099999999998, -165.58599999999998, -165.50900000000001,
              -165.44400000000002,             -164.76, -164.62099999999998,
                          -164.62,
              ...
                         -67.7617,            -67.4012,            -67.3318,
                         -67.2996,             -67.275,            -67.2711,
                          80.9491,               90.37,             96.7591,
                          97.4331],
             dtype='float64', length=112347)]]



[['participant_age', Index(['0.041666667', '0.042361111', '0.043055556', '0.04375', '0.044444444',
       '0.045138889', '0.045833333', '0.046527778', '0.047916667',
       '0.048611111',
       ...
       '7::22||8::28||9::28||10::26', '7::27', '7::31', '8::15', '8::18',
       '8::22', '8::27', '8::29', '9::20||10::20', '9::28'],
      dtype='object', length=18951)]]



[['participant_age_group', Index(['0::Adult 18+', '0::Adult 18+||1::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||15::Adult 18+||16::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||3::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||3::Adult 18+||4::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||3::Adult 18+||4::Adult 18+||5::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||3::Adult 18+||4::Adult 18+||5::Adult 18+||6::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||3::Adult 18+||4::Adult 18+||5::Adult 18+||6::Adult 18+||7::Adult 18+',
       '0::Adult 18+||1::Adult 18+||2::Adult 18+||3::Adult 18+||4::Adult 18+||5::Adult 18+||6::Adult 18+||7::Adult 18+||11::Adult 18+',
       ...
       '6::Adult 18+||7::Adult 18+', '6::Adult 18+||7::Teen 12-17',
       '6::Teen 12-17', '6::Teen 12-17||7::Adult 18+',
       '6::Teen 12-17||7::Teen 12-17', '7::Adult 18+', '8::Adult 18+',
       '8::Adult 18+||9::Adult 18+||10::Adult 18+', '8::Teen 12-17',
       '9::Adult 18+'],
      dtype='object', length=898)]]

#### ANALYZING THE OVERVIEW OF THE DATA

SHAPE

From the above output, the 9 variables of my data comprises of 4 numerical variables and 5 categorical variables.

MISSING VALUE

I have 7% of missing data. participant_age has a total of 38.5% of its inputs missen and that is the highest. For this reason and the fact that participant_age_group is a better variable to capture age, I would be removing this variables. This is because, with such high number of missing values, any analysis done with these variable can be highly misleading with high errors.

After this, I would further remove any additional rows with missing values.

FIELD VALUES

The participant_age variable appears to have some unreasonable values. For instance:['0.041666667', '0.042361111', '0.043055556', '0.04375', '0.044444444', '0.045138889', '0.045833333', '0.046527778', '0.047916667','0.048611111'] I would need to remove such inputs should they still exist after dealing with missing values and duplicates.

To help me deal with these issues for the remaining variables in the object format, I would need to convert their categories to sub-categories to fish out these unreasonable inputs and also facilitate my analysis.

DUPLICATES

The data currently has 864 duplicate rows. After dealing with the missing values, this may reduce the remaining duplicates and then, i would remove these duplicates.

### 2. Data Cleaning
Given, the issues I have raised above, I will be doing the relevant data cleaning needed to help smoothen my subsequent analysis.
First, I will deal with missing values.
Next, unreasonable column values
Lastly, duplicates.
Also, I may subset certain coulmns where necessary.

DEALING WITH MISSING VALUES

In [24]:
new_guns=new_guns.drop(['participant_age'], axis=1)

In [25]:
new_guns=new_guns.dropna()

In [26]:
new_guns.shape

(190571, 8)

DEALING WITH DUPLICATES

In [27]:
new_guns.drop_duplicates

<bound method DataFrame.drop_duplicates of              date                 state            city_or_county  n_killed  \
0      2013-01-01          Pennsylvania                Mckeesport         0
1      2013-01-01            California                 Hawthorne         1
2      2013-01-01                  Ohio                    Lorain         1
3      2013-01-05              Colorado                    Aurora         4
4      2013-01-07        North Carolina                Greensboro         2
5      2013-01-07              Oklahoma                     Tulsa         4
6      2013-01-19            New Mexico               Albuquerque         5
8      2013-01-21            California                 Brentwood         0
9      2013-01-23              Maryland                 Baltimore         1
10     2013-01-23             Tennessee               Chattanooga         1
11     2013-01-25              Missouri               Saint Louis         1
12     2013-01-26             Louisiana                 Charenton         2
13     2013-01-26  District of Columbia                Washington         0
14     2013-01-26                  Ohio               Springfield         1
15     2013-02-02             Tennessee                   Memphis         0
16     2013-02-03            California             Yuba (county)         1
17     2013-02-07              Illinois                   Chicago         0
18     2013-02-09             Louisiana               New Orleans         0
19     2013-02-11            California                   Vallejo         1
20     2013-02-11              Delaware                Wilmington         3
21     2013-02-12                  Utah                   Midvale         4
22     2013-02-19            California           Orange (county)         4
23     2013-02-21              Oklahoma                     Tulsa         1
24     2013-02-22              Michigan              Grand Rapids         0
25     2013-02-23            California                 Lancaster         0
26     2013-02-24               Georgia                     Macon         0
27     2013-03-02             Louisiana                Shreveport         1
28     2013-03-03               Georgia                  Moultrie         2
29     2013-03-03              Michigan          Saginaw (county)         0
30     2013-03-04            California                 Los Banos         1
...           ...                   ...                       ...       ...
239629 2018-03-31         Massachusetts               Springfield         0
239630 2018-03-31              Michigan                   Detroit         1
239634 2018-03-31                 Texas                  Pasadena         1
239635 2018-03-31               Florida               Tallahassee         1
239636 2018-03-31               Indiana              Indianapolis         0
239638 2018-03-31            California                 Earlimart         1
239639 2018-03-31            California                   Salinas         0
239640 2018-03-31         Massachusetts                    Boston         1
239641 2018-03-31             Tennessee                    Martin         0
239643 2018-03-31              New York               Lindenhurst         1
239645 2018-03-31              New York                  Brooklyn         1
239646 2018-03-31          Pennsylvania                  Duquesne         1
239650 2018-03-31            California                  Palmdale         1
239651 2018-03-31                 Texas             Wichita Falls         0
239652 2018-03-31                 Texas                    Dallas         0
239653 2018-03-31                Nevada                      Reno         1
239654 2018-03-31                Nevada                      Reno         1
239655 2018-03-31            California                 San Diego         0
239657 2018-03-31            California                   Shafter         0
239659 2018-03-31               Florida                   Orlando         0
239660 2018-03-31            California                  Stockton         2
239662 2018-03-31             Minnesota                Saint Paul         0
239663 2018-03-31              Oklahoma                   Guthrie         1
239664 2018-03-31              Missouri                    Festus         0
239667 2018-03-31             Tennessee                   Memphis         0
239671 2018-03-31            Washington  Spokane (Spokane Valley)         0
239673 2018-03-31             Louisiana              Natchitoches         1
239674 2018-03-31             Louisiana                    Gretna         0
239675 2018-03-31                 Texas                   Houston         1
239676 2018-03-31                 Maine              Norridgewock         2

        n_injured  latitude  longitude  \
0               4   40.3467   -79.8559
1               3   33.9090  -118.3330
2               3   41.4455   -82.1377
3               0   39.6518  -104.8020
4               2   36.1140   -79.9569
5               0   36.2405   -95.9768
6               0   34.9791  -106.7160
8               4   37.9656  -121.7180
9               6   39.2899   -76.6412
10              3   35.0221   -85.2697
11              3   38.7067   -90.2494
12              3   29.8816   -91.5251
13              5   38.8978   -76.9717
14              3   39.9252   -83.8218
15              5   35.0803   -89.8871
16              3   39.1236  -121.5830
17              4   41.7592   -87.5628
18              4   29.9563   -90.0676
19              4   38.1072  -122.2280
20              2   39.7407   -75.5499
21              1   40.6008  -111.9030
22              3   33.8031  -117.9430
23              3   36.1722   -95.8778
24              4   42.9371   -85.6853
25              4   34.6666  -118.1310
26              8   32.8260   -83.6704
27              3   32.4420   -93.7726
28              2   31.1824   -83.7912
29              4   43.3944   -83.9082
30              3   37.0857  -120.8280
...           ...       ...        ...
239629          1   42.0925   -72.5803
239630          0   42.3301   -83.1486
239634          1   29.6872   -95.2024
239635          0   30.4490   -84.3068
239636          2   39.8850   -86.1967
239638          0   35.8791  -119.2650
239639          0   36.6191  -121.6360
239640          0   42.2812   -71.0836
239641          0   36.3500   -88.8510
239643          1   40.7039   -73.3743
239645          0   40.6409   -73.9565
239646          0   40.3740   -79.8505
239650          0   34.5713  -118.0450
239651          1   33.9052   -98.5151
239652          1   32.6772   -96.8059
239653          0   39.4832  -119.7800
239654          0   39.5537  -119.7760
239655          0   32.8936  -117.1360
239657          0   35.5019  -119.2830
239659          3   28.5279   -81.4594
239660          0   37.9478  -121.3140
239662          2   44.9685   -93.0609
239663          0   35.8739   -97.4163
239664          1   38.2074   -90.4990
239667          1   35.2045   -89.9872
239671          0   47.6638  -117.2350
239673          0   31.7537   -93.0836
239674          1   29.9239   -90.0442
239675          0   29.7201   -95.6110
239676          0   44.7293   -69.7691

                                    participant_age_group
0       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
1       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
2       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
3       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
4       0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...
5       0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
6       0::Adult 18+||1::Adult 18+||2::Child 0-11||3::...
8       0::Teen 12-17||1::Teen 12-17||2::Teen 12-17||4...
9       0::Teen 12-17||1::Adult 18+||2::Adult 18+||3::...
10                                           0::Adult 18+
11                                           0::Adult 18+
12      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
13      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
14      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
15      0::Adult 18+||1::Adult 18+||2::Adult 18+||4::A...
16      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
17      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
18      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
19      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
20      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
21      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
22      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
23      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
24                             0::Adult 18+||1::Adult 18+
25      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
26      0::Adult 18+||2::Adult 18+||3::Adult 18+||4::A...
27      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
28      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
29      0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...
30      0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
...                                                   ...
239629  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
239630                                       0::Adult 18+
239634                         0::Adult 18+||1::Adult 18+
239635                                       0::Adult 18+
239636                         0::Adult 18+||1::Adult 18+
239638                                       0::Adult 18+
239639                         0::Adult 18+||1::Adult 18+
239640                                       0::Adult 18+
239641                                       0::Adult 18+
239643                         0::Adult 18+||1::Adult 18+
239645                                       0::Adult 18+
239646                                      0::Teen 12-17
239650                         0::Adult 18+||1::Adult 18+
239651                         0::Adult 18+||1::Adult 18+
239652                         0::Adult 18+||1::Adult 18+
239653                                       0::Adult 18+
239654                                       0::Adult 18+
239655                                       0::Adult 18+
239657                                       0::Adult 18+
239659           0::Adult 18+||1::Adult 18+||2::Adult 18+
239660                         0::Adult 18+||1::Adult 18+
239662                         0::Adult 18+||1::Adult 18+
239663                                       0::Adult 18+
239664                         0::Adult 18+||1::Adult 18+
239667                         0::Adult 18+||1::Adult 18+
239671                                       0::Adult 18+
239673                         0::Adult 18+||1::Adult 18+
239674                                       0::Adult 18+
239675                                       0::Adult 18+
239676                         0::Adult 18+||1::Adult 18+

[190571 rows x 8 columns]>

In [28]:
new_guns.shape

(190571, 8)

From above output, it is clear that the duplicates no longer exist after the initial cleaning.

**Let's have an overview of new data**

In [29]:
new_guns.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 190571 entries, 0 to 239676
Data columns (total 8 columns):
date                     190571 non-null datetime64[ns]
state                    190571 non-null object
city_or_county           190571 non-null object
n_killed                 190571 non-null int64
n_injured                190571 non-null int64
latitude                 190571 non-null float64
longitude                190571 non-null float64
participant_age_group    190571 non-null object
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 13.1+ MB

**Next, I want to do any needed subsetting of my data for easy visualization and analysis**

In [30]:
new_guns["month-year"]=pd.to_datetime(new_guns['date']).dt.to_period('M')
new_guns.head(2)

,date,state,city_or_county,n_killed,n_injured,latitude,longitude,participant_age_group,month-year
0,2013-01-01,Pennsylvania,Mckeesport,0,4,40.3467,-79.8559,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,2013-01
1,2013-01-01,California,Hawthorne,1,3,33.9090,-118.3330,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,2013-01

In [31]:
new_guns.shape

(190571, 9)

At the end of cleaning the data, my new data contains 9 variables and 190571 observations.


**END OF DATA CLEANING**

Reference

Retrieved from [Source code](https://www.dataquest.io/blog/python-datetime-tutorial/)

Retrieved from [Source code](https://github.com/pandas-profiling/pandas-profiling)

cmdline(2018).Python and R Tips. Retrieved from [Source code](https://cmdlinetips.com/2018/04/how-to-drop-one-or-more-columns-in-pandas-dataframe/amp/)